# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Aiman's Blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog post that host almost all of my previous code-related project in the duration of my university course and posibly even further in the future.
baseurl: "/port_blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# paginates setting
paginate: 5


# Used from minima theme
social_links:
    github:  maiman-1
    linkedin: muhammad-aiman-bin-shamsiemon-2899a6197
    email: maimansham@gmail.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

defaults:
  -
    scope:
      # Tell us which file we want default front matter to apply to
      path: ""
      type: "posts"
    values:
      # Any values that we want to store
      layout: "default"
      author: "Muhammad Aiman Shamsiemon"
      permalink:  /:categories/:title.html

sass:
  sass_dir: assets/css


# Include images
include:
  - _static

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
